### ISSUE TITLE
Add documentation of how to include font on pages for Heading and Text

### ISSUE THREAD

**Issue by tamm** [brighte-labs/spark-web#79]
## What is missing?

A description of a correct / expected / suggested method to import the fonts used for Text (and Heading) in the documentation.

https://github.com/brighte-labs/spark-web/blob/main/packages/heading/README.md
https://github.com/brighte-labs/spark-web/blob/main/packages/text/README.md

## What is there?

In the source code of the documentation page one font is embedded from Google Fonts, this is obviously easy to simply mention. The other font is imported from Vercel, which means we're expecting to self host this.

**Comment by lukebennett88** [comment]
Hey @tamm, thanks for raising this issue.
We definitely have a bit of work to do in terms of documenting more of the design system.
So far we've punted on documenting how to load the fonts because the current system is a bit of a hack and is going to chance soon.
We're planning to get the fonts loaded onto a subdomain of brighte.com.au and will document how to load the fonts once that's done.
There is a ticket here if you're interested in following:
https://brighte.atlassian.net/browse/SPRK-42
